# Generated by Django 6.1 on 2026-08-10 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('concept_key', models.CharField(default='OTHER', max_length=100)),
                ('initial_score', models.FloatField(default=0)),
                ('final_score', models.FloatField(blank=True, null=True)),
                ('viva_score', models.FloatField(blank=True, null=True)),
                ('misconception', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='Attempted', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='labtwin.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ConceptProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept_key', models.CharField(max_length=100)),
                ('attempts', models.IntegerField(default=0)),
                ('mastered', models.IntegerField(default=0)),
                ('failures', models.IntegerField(default=0)),
                ('misconception_count', models.IntegerField(default=0)),
                ('last_misconception', models.TextField(blank=True, default='')),
                ('total_score', models.FloatField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_progress', to='labtwin.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'concept_key')},
            },
        ),
    ]
