# Generated by Django 6.1 on 2026-08-12 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtwin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='hint_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attempt',
            name='independent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attempt',
            name='mastery_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='attempt',
            name='topic',
            field=models.CharField(default='General', max_length=200),
        ),
        migrations.AddField(
            model_name='attempt',
            name='verification',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TopicProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('concept_key', models.CharField(default='OTHER', max_length=100)),
                ('attempts', models.IntegerField(default=0)),
                ('mastery_score', models.FloatField(default=0)),
                ('status', models.CharField(default='Not Tested', max_length=50)),
                ('verification_required', models.BooleanField(default=False)),
                ('verification_passed', models.BooleanField(default=False)),
                ('misconception_count', models.IntegerField(default=0)),
                ('last_misconception', models.TextField(blank=True, default='')),
                ('average_hint_level', models.FloatField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_progress', to='labtwin.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'topic')},
            },
        ),
    ]
